[package]
name = "actix"
version = "0.1.0"
authors = ["Johan Planchon <johan.planchon@simplx.fr>"]
edition = "2018"

[dependencies]
actix-web = { version = "3.2.0", default-features = false, features = [] }